### PR TITLE
Feature 0075 - Allow resizable display on atari environments

### PR DESCRIPTION
**Pull request by JKCooper2**
PR for https://github.com/openai/gym/issues/75

Run env.set_display_dimensions(width, height) on atari environments to customise display size. 

Atari uses SimpleImageViewer which takes in no constructor arguments whereas classic control uses Viewer which takes in width and height as constructor arguments (but these are defined by the environment rather than the user). 

I'm not sure whether it's worth trying to combine the functionality together so users can define display size for all environments. If so it may be easiest to always display output through SimpleImageViewer and just use it as a resizer for [width, height, rgb] pixel array

### CODE REVIEW

**Comment by JKCooper2** [comment]
I'm not sure whether isopen should be set to True as the display dimensions can be set anytime after the environment is created, not necessarily when the window is first opened. However the only place I could see that being used is in closed so for that usage it will still perform in the same way

**Comment by gdb** [comment]
@joschu mind reviewing?

**Comment by joschu** [comment]
OK, assigned to myself.

**Comment by gdb** [comment]
Thanks for the implementation. This is a pretty reasonable implementation. Unfortunately, I think it's a feature we don't want to support yet. I'm going to close this for now, and revisit if there's a lot of demand.

**Comment by StuartFarmer** [comment]
Can we get this so we're not working with a dinky view?

**Comment by gdb** [comment]
Will wait for more upvotes — I still don't think there's enough demand for us to support it.

**Pull request closed without merging**
