### PR TITLE
Python 3.9 support

### PR DESCRIPTION
**Pull request by justinkterry**
Includes the changes in #1804 rebased on master. If tests fail I'll deal with it.

### CODE REVIEW

**Comment by justinkterry** [comment]
@pzhokhov I believe this is ready to merge?

**Comment by justinkterry** [comment]
@pzhokhov just following up on this

**Comment by justinkterry** [comment]
@pzhokhov it's been a month, just following up.

**Review by pzhokhov — APPROVED** [review]

**Comment by pzhokhov** [comment]
@justinkterry the release to pypi can happen after this: https://github.com/openai/gym/pull/2133

**Pull request merged**
