### PR TITLE
Try to fix the recursive import error on Python 2

### PR DESCRIPTION
**Pull request by pcmoritz**
Be careful with this, it might break other things.

There should also be a proper way of getting all the dependencies sorted out nicely.

### CODE REVIEW

**Comment by simontudo** [comment]
Solved the error for me! Thanks a lot!

**Comment by Astronirav** [comment]
It kinda solved the issue for me. But when I tried running this code: [https://gist.github.com/awjuliani/4d69edad4d0ed9a5884f3cdcf0ea0874#file-q-net-learning-clean-ipynb](url)
I got following error:
screenshot from 2018-02-01 18 53 31

**Comment by frostburn** [comment]
This solution feels like a hack.
Usually the proper way to resolve circular imports is to move the offending entity into a separate module that has no further imports.
You can also try moving one of the imports out of module level inside a method so that the module loading can complete without actually running the circular part.

**Comment by pcmoritz** [comment]
The proper fix is being developed here: https://github.com/openai/gym/pull/858

**Pull request closed without merging**
