### PR TITLE
human / batch mode using _display_options #185

### PR DESCRIPTION
**Pull request by olegklimov**
#185

### CODE REVIEW

**Comment by jietang** [comment]
It seems to me like these options don't apply to all environments, and I'd rather not add complexity to the core interfaces unless it adds functionality that is broadly useful.

If you're concerned about code duplication, what do you think about implementing this as a helper class that can be used by classic_control and box2d envs?

**Comment by olegklimov** [comment]
It is not a real PR at the moment, just an idea about reorganizing the code, to throw something specific to https://github.com/openai/gym/issues/185.

I don't really like interfering with others code, in this case @gdb. He has added display_n recently for some reason (docker container?). The idea is that batch mode and window position look like other display flags. We should hear what he thinks first.

(But of course it applies to most environments! Atari, doom, all benefit from ability to place window at predictable place, batch mode. It applies to any environment that have a window and fps.)

**Comment by gdb** [comment]
Yep, I added `display` for docker container. I agree with Jie's comment completely — we should only add things that are basically universal to the core interfaces.

In this case, I'd recommend just adding a `def configure(display_n, display_mode, ...)` or whatever (I don't love the `display_mode` name since it's kinda generic — what about `framerate` or something more specific) with the set of options as appropriate to each class.

**Comment by olegklimov** [comment]
Okey, I'll do another.

**Pull request closed without merging**
