### PR TITLE
Description for mountain_car.py

### PR DESCRIPTION
**Pull request by Revanthmk**
Added description for the mountain_car environment. As a beginner this description would have saved a lot of time for me understanding the environment.

### CODE REVIEW

**Comment by justinkterry** [comment]
@pzhokhov can this be merged?

**Comment by Revanthmk** [comment]
@justinkterry I believe It can be. " Able to merge. These branches can be automatically merged."

**Comment by justinkterry** [comment]
No I know, I was asking for it to be merged

**Comment by Revanthmk** [comment]
oh yeah, my bad sorry.

**Pull request merged**
