### PR TITLE
Added ViZDoom environments

### PR DESCRIPTION
**Pull request by ppaquette**
Added 9 doom environments, based on ViZDoom

Depends on 'doom-py' (https://github.com/ppaquette/doom-py) which is not yet published

### CODE REVIEW

**Comment by gdb** [comment]
Awesome! Thanks so much for doing this.

We'll poke around and get back to you shortly.

**Comment by wojzaremba** [comment]
This stuff looks sooooooo good. We will definitely have a look on it very soon.

**Comment by JKCooper2** [comment]
I'm getting an error when running: pip install -e '.[doom]' inside the gym folder:
>  Could not find a version that satisfies the requirement doom-py>=0.0.1 (from gym==0.0.7) (from versions: ) No matching distribution found for doom-py>=0.0.1 (from gym==0.0.7).
Where should I install doom-py from?
VizDoom looks amazing. I wonder if it could be used for things like model generalisation over different screen dimensions

**Comment by gdb** [comment]
I've broken this into a separate plugin package for now: https://github.com/openai/gym-doom, so it's easy for people to play with until. Once people feel good about the tasks, we'll either bring it back into core, or maybe decide that plugins are actually the way to go.

**Comment by gdb** [comment]
Closing in favor of #92. We should have these out soon. cc/ @jietang

**Pull request closed without merging**
