### PR TITLE
Makes Box2D environments pickleable.

### PR DESCRIPTION
**Pull request by jachiam**
Used EzPickle to make Box2D environments pickleable.

### CODE REVIEW

**Comment by olegklimov** [comment]
Hi Josh. Does it restore state back to a pickled one?

**Comment by jachiam** [comment]
It doesn't - if I understand correctly, EzPickle unpickles by creating a new instance of the Box2D env via the constructor. None of the constructors take any arguments to restore state, so EzPickle couldn't be used to do that. 

But I think this is reasonable behavior, considering that the other main gym environments (MuJoCo and Atari) do the same thing. The only reason it would be bad is if the Box2D envs do some kind of implicit curriculum, where the distribution over random environment parameters changes over training. Are any of them like this?

**Comment by olegklimov** [comment]
> parameters changes over training

No, they are simple.

Well I'm OK with this, let's see if Peter will merge it.

**Comment by pzhokhov** [comment]
LGTM

**Pull request merged**
