### PR TITLE
Action wrappers

### PR DESCRIPTION
**Pull request by ngc92**
Thre wrappers that change the apparent action space used by an env. With this it is possible to train an agent that is designed for single discrete actions on multi-discrete or even continuous envs. For the latter it is also possible to rescale the actions, e.g. to always assume actions in the range [0, 1] for the agent.

What is currently not implemented is interpreting a discrete space as continuous, any transformations of TupleSpace and the reverse_action method. If there is interest in any of that I can implement it, at least to a degree to which it is sensible (e.g. flattening a tuple space with continuous and discrete subspaces does not make sense).

### CODE REVIEW

**Comment by gdb** [comment]
Thanks for the wrappers! We're actually trying to keep the core lightweight and stable, so I would recommend instead making a separate repository for these wrappers, which people can then import. (I've updated the README to no longer suggest that people submit wrappers for us to add.)

**Comment by ngc92** [comment]
That makes sense if you strive for maximum stability in the core code. It would probably still be useful to have some kind of central registry for these kinds of utilities (downsampling, conversion to grayscale also come to mind here). Either another repo, or mazbe simply a list or wiki page with links towards the respective repos.

**Comment by gdb** [comment]
Yep, please feel free to start a wrappers.md here: https://github.com/openai/gym/tree/master/docs!

**Comment by pzhokhov** [comment]
per @gdb's point closing this (I have merged #631 )

**Pull request closed without merging**
