### PR TITLE
Add AtariNoFrameskip-v0

### PR DESCRIPTION
**Pull request by nottombrown**

### CODE REVIEW

**Comment by nottombrown** [comment]
@gdb A request from Rafal - This naming seem plausible?

**Comment by gdb** [comment]
I think "Deterministic" and "NoFrameskip" are kinda redundant. Maybe just call it "NoFrameskip"?

**Comment by nottombrown** [comment]
Updated, will merge in after CI finishes

**Comment by nottombrown** [comment]
Merged this in, @gdb could you push a new version of the gym so that researchers can get it from pip?

**Pull request merged**
