### PR TITLE
Added an environment for the board game Go

### PR DESCRIPTION
**Pull request by aigagror**

### CODE REVIEW

**Comment by aigagror** [comment]
Hello can someone the OpenAI team say whether this environment can be added or not?

**Comment by christopherhesse** [comment]
Looks good, could you add it to the bottom of the list?  I think we've been adding them there until we have some better method for sorting them.

**Comment by aigagror** [comment]
Ok I did that

**Comment by aigagror** [comment]
On a side note, I was wondering if third party environments every get added to the official list. If so, how does that process work?

**Comment by pzhokhov** [comment]
@aigagror thanks!  What do you mean by the official list? To the gym itself, to the gym website (http://gym.openai.com)? If the former (to the gym itself), then basically that does not happen anymore, in fact, we are trying to slowly move environments out of the gym (and only keep Env interface, wrappers and tools). If the latter (to the gym website), then the link to the third-party environments is already there.

**Pull request merged**
