### PR TITLE
Move all tests to gym/tests/...

### PR DESCRIPTION
**Pull request by RedTachyon**
See Issue #2424

This is kinda WIP, we have to make sure that all the tests actually trigger and pass.

Also from a quick local test it seems that some of the tests have internal imports. PyCharm did its best to convert them, but it might need some more attention.

### CODE REVIEW

**Comment by jkterry1** [comment]
@RedTachyon this tentatively looks good to me, however the first 4 file renames shown in the files changed tab don't make a lot of sense to me?

**Comment by RedTachyon** [comment]
@jkterry1 Do you mean `gym/envs/tests/__init__.py → gym/tests/__init__.py` etc?

It's marked as renames, but my guess is that it's the `diff` failing to understand moved files. There was a bunch of inits in the previous version under `gym/envs/tests`, `gym/wrappers/tests`, and now there's a bunch of inits under `gym/tests/envs`, `gym/tests/wrappers` and so on. So it tried to map the former to the latter, but it got a bit wonky in the process because in the end it's just all empty `__init__`s

**Comment by jkterry1** [comment]
I mean things like "gym/spaces/tests/__init__.py → gym/tests/envs/__init__.py"

**Comment by jkterry1** [comment]
Oh, no that should be a bad diff. You're right.

**Pull request merged**
