### PR TITLE
add pygame GUI for frozen lake env

### PR DESCRIPTION
**Pull request by younik**
As suggested by @jkterry1, I added a pygame GUI for the Frozen Lake environment

Any suggestions for appearance improvements are welcome :)

Screenshot from 2022-01-15 20-14-27

### CODE REVIEW

**Comment by jkterry1** [comment]
@younik can you please fix tests?

**Comment by trigaten** [comment]
It would be good to use simple pixel textures like (Pettingzoo)[https://www.pettingzoo.ml/#] does.
Here are a couple relevant PettingZoo textures:
river_tile
Simple

**Comment by younik** [comment]
> What happened in the diff here?

Great question 😅
I think I forgot to "update" after changing the origin

**Comment by younik** [comment]
> It would be good to use simple pixel textures like [Pettingzoo](https://www.pettingzoo.ml/#) does. Here are a couple relevant PettingZoo textures: Water water Person person
> 
> Ill look for ice art.

Thanks!
I added a mock art for ice; if you find a better one send it!

Screenshot from 2022-01-21 11-22-23

**Comment by jkterry1** [comment]
@younik you need to fix the gif

**Comment by jkterry1** [comment]
diff*

**Comment by younik** [comment]
> @younik you need to fix the gif

Ok, I think I have to do another pull request. I close this one.

**Pull request closed without merging**
