### PR TITLE
Scale height reported by state to viewport height rather than width

### PR DESCRIPTION
**Pull request by peejaybee**
The scaling in the reported state looks off to me.  It shouldn't matter to the solution, since it's just scaling by a different constant, but seems like the vertical velocity and height should be in compatible scales.

### CODE REVIEW

**Comment by olegklimov** [comment]
You're probably right, that's a typo. 

Description says landing pad is at (0,0), so a very wrong thing would be zero out of place. But that's not the case, just scale is wrong. 

IMO, change is correct, but it's not worth environment version increase. Maybe put this in comment and apply anytime we increase version for some other reason?

**Comment by peejaybee** [comment]
That makes sense, or we can just keep this PR open and I can rebase when it's time for a version bump.

**Comment by pzhokhov** [comment]
has been fixed upstream; closing this

**Comment by pzhokhov** [comment]
or actually version upstream has VIEWPORT_H/SCALE/2, whereas the PR has VIEWPORT_H/SCALE... @olegklimov could you comment whether that's important?

**Comment by olegklimov** [comment]
I think it's correct as it is. Observation scale is the same for x and y, which is good. The modified version would be just as learnable and largely equivalent, isn't worth the change.

**Comment by pzhokhov** [comment]
ok then, closing this

**Pull request closed without merging**
