### PR TITLE
Typing in gym.core.Env

### PR DESCRIPTION
**Pull request by ikamensh**
Adds type hints to `gym.core.Env` class. Type checked with pyright.
Part of #2452 . Implementation inspired by comment from @lebrice

### CODE REVIEW

**Comment by RedTachyon** [comment]
@ikamensh regarding #2486, #2487, #2488, #2489, could you please put them all together into a single PR? It would be much easier to process and review, especially since some of these PRs don't actually work in isolation. Also it would be easier to avoid a merge conflict hell with other work going on in the meantime.

**Comment by jkterry1** [comment]
@ikamensh seconded, that would be very appreciated. Sorry it took as so long to get to look at these

**Comment by ikamensh** [comment]
Can do, but I actually thought it would be easier with split PRs - if some of them need rework, parts can already be merged and therefore less work in progress needs rebasing. I'll have time in a week or so but if some of it can be merged as is would also be appreciated.

**Comment by jkterry1** [comment]
All of them but the space PR (#2487) have merge conflicts; Ariel could you please take a look at that one in the mean time?

**Pull request closed without merging**
