### PR TITLE
Set restriction on selected actions for MountainCar-v0

### PR DESCRIPTION
**Pull request by JKCooper2**
Restricts accepted actions for MountainCar-v0 to be from the set (0, 1, 2) throwing a ValueError if the submitted action is outside of that range

### CODE REVIEW

**Comment by gdb** [comment]
Cool. Rather than throwing a `ValueError` though, I think we should add an `InvalidAction` exception to error.py, and throw that here.

**Comment by jonasschneider** [comment]
This check would be generic enough to do in `core.py`. Thoughts on that? We discussed oddly-shaped numpy arrays before, but I'd consider it undefined behavior to `step` with actions not `contain`ed in the `action_space`.

Maybe we can add a generic warning to `core.py`, and raise as a special case for discrete action spaces (where passing in something illegal ~always indicates breakage)?

**Comment by gdb** [comment]
Good point, I'd forgotten we now have hooks there. I think yes, what you suggest in the right way to go.

**Comment by JKCooper2** [comment]
I've moved the action validation into core.py and added a specific exception to error.py. Was this the kind of thing you were meaning?

As long as all action spaces implement .contains() which is currently required then it will be valid for all scenarios

**Comment by jonasschneider** [comment]
This looks good! Though I think we'll change the raised exception to just be a warning, for backwards compatibility. Thanks!

**Comment by JKCooper2** [comment]
Would warnings require logger to be imported into core? I can only seen warn used with logger.warn()
Also if it's a warning should it still pass the invalid action through to the environment? It doesn't feel right to make it randomly choose a valid action to ensure the environment can operate effectively

**Comment by jonasschneider** [comment]
Yeah, we definitely don't want to silently change the values that are passed through. Therefore we'll just try to "keep trucking on" with the invalid value -- if it breaks, the warning will guide the user to the fix.
https://github.com/openai/gym/commit/4519a6ffe377ccf370e507c705709bc673c904d5 shows how I imagine this -- does this look reasonable?

**Comment by JKCooper2** [comment]
Yes that seems fine. Most agents will break from invalid values in any case and can provide customised reasons in there. At least this enforces awareness of invalid action selection over all environments.

**Pull request merged**
