### PR TITLE
minor changes to cartpole+acrobot, upgrade to v1

### PR DESCRIPTION
**Pull request by joschu**
cartpole: bump timestep limit to 500, so you need to have a decent balancing policy to solve it
acrobot: change observation to use cos/sin of angles, and increase timestep limit so acrobot gets solved by random exploration

### CODE REVIEW

**Comment by gdb** [comment]
Do you think it's worth keeping around the old CartPole-v0 as well?

**Comment by gdb** [comment]
(Might be nice to keep existing code running, even though it's deprecated.)

**Comment by joschu** [comment]
Might as well, since we're not even changing cartpole.py

**Comment by rafaelcp** [comment]
Acrobot-v0 got removed! Can you restore it?

**Comment by gdb** [comment]
That was intentional — why do you want Acrobot-v0?

**Pull request merged**
