### PR TITLE
Added the Retro Learning Environment (SNES games) to gym

### PR DESCRIPTION
**Pull request by nadavbh12**

### CODE REVIEW

**Comment by tlbtlbtlb** [comment]
Wow! Looks awesome!

It looks like you copied the many different versions (Deterministic, NoFrameskip, -v0, -v3) from the Atari versions. Most of these are there for backwards compatibility. Can we cut all the ones that aren't necessary and use -v0 for all of them? Specifically, I think all these might be unnecessary: https://github.com/nadavbh12/gym/blob/4918e31158772b1251921b7308d4d3f397b37270/gym/envs/__init__.py#L363-L411

Our Travis check is failing because we don't install the dependency. I'll try to add that soon.

**Comment by nadavbh12** [comment]
Thanks Trevor!

I wasn't sure what the version were. I've removed them in the latest commit.

Travis is failing since rle_python_interface requires some manual installation.
I'm not very experienced with Python distutils and was having a hard time incorporating the cmake installation with it so it will install automatically.
Is being able to install with 'pip install' strictly required?

**Comment by joschu** [comment]
This is great! Currently it's still too hard to install RLE and its dependencies. Could you please provide a script that downloads and installs the relevant parts of libretro to build the SNES core, along with at least one ROM (so people can get something running right away?) If you don't want to risk posting the nintendo ROMs on github, you could probably find a public-domain ROM.

**Comment by nadavbh12** [comment]
Hey John,
The CMake file downloads and compiles our (now 3) supported emulators: Stella, SNES9x and Genesis-Plus-Gx.
I'm currently working on calling installing them along with RLE using distUtils, however, integration with CMake is quite horrible.
I can provide a simple shell script which simply calls CMake, setup.py and copies the core files to known locations. Will that suffice?
nice idea with the public domain ROM. We'll add support for one for ease of use.

**Comment by joschu** [comment]
Ah OK, didn't notice the CMake file did all of that. I remember it was a bit of a pain to get Atari to work properly with pip. Let me consult with my colleagues (who know more about python installation) about this, and I'll also try installing RLE.

**Comment by nadavbh12** [comment]
Great. Note though that my attempts to easily install RLE might have broken the "standard" installation, so it's better to checkout v1.0.2.
The latest version can be installed from Pypi using `pip install rle_python_interface`.
Though I haven't figured out yet why the cores don't install with it.

**Comment by nadavbh12** [comment]
I updated RLE so you can install via pypi and added a ROM of the game Classic Kong.
Not sure what's failing in travis. Please have a look.

**Comment by nadavbh12** [comment]
@joschu, while on my computer `pip install -e '.[all]'` installs RLE, it doesn't seem to do so [on travis](https://travis-ci.org/openai/gym/builds/204576253#L393).
Could you have a look and see why's this?

**Comment by nadavbh12** [comment]
@joschu , @tlbtlbtlb ,
Hopefully the branch should be working now correctly using both Python 2 & 3, using pip install (classic kong rom included).
Not sure why travis won't run this. Could you give it a look?

**Comment by joschu** [comment]
Hi Nadav, we probably won't be merging in other environments like this -- we're realizing that it makes sense to host them in separate repositories so their authors can more easily develop them. We'll make sure to advertise your environment prominently. Sorry if you've had to waste time trying to get your code to run in our CI.

John

**Comment by tlbtlbtlb** [comment]
See https://github.com/openai/gym/tree/master/gym/envs#how-to-create-new-environments-for-gym for guidelines on structuring add-on packages for gym. So we'll hope you'll make a repo called gym-rle or gym-snes that, when imported, registers the environments.

**Comment by nadavbh12** [comment]
Thanks. Well, that actually makes sense.
No harm done since your CI helped me find a few bugs and from what is seems integrating environments in both methods highly overlap.
Will open the new repository soon.

**Comment by nadavbh12** [comment]
@tlbtlbtlb,
I created a [gym-rle repo](https://github.com/nadavbh12/gym-rle). 
Hopefully, once it's up and running we can add more interesting challenges :-)

**Pull request closed without merging**
