### PR TITLE
Refactor mujoco envs to support dynamic arguments

### PR DESCRIPTION
**Pull request by hartikainen**
I'm glad to see that gym finally supports dynamic parameterization of the environments (#1301).

We've been using custom parameterizable versions of the basic mujoco environments in our [softlearning codebase](https://github.com/rail-berkeley/softlearning/tree/master/softlearning/environments/gym/mujoco) for a while now, and I thought I would share those environments here as well. The implementations are imo a bit more readable and they support parameterization of the environments via init args. For example, certain environments can be made to not terminate and all the rewards and costs can be tuned via init arguments. With the default parameters, these environments are exact copies of the original environments (I've verified the step and reset functions by testing them against the old implementations).

Currently, the only refactored environments are Ant, Hopper, HalfCheetah, Humanoid, Swimmer, and Walker2d. I'm happy to refactor the rest of the mujoco environments if these seem useful.

### CODE REVIEW

**Comment by pzhokhov** [comment]
this looks neat to me! I am a little hesitant about the exact reproduction of the original mujoco envs - could you add some unit tests to that extent? For instance, instead of replacing the old mujoco envs you could create the -v3 version of them, and add unit tests that compare v2 and v3. If all of them pass, we can create a separate PR removing the non-configurable versions.

**Comment by hartikainen** [comment]
@pzhokhov thanks for the comment. I moved the new environments under v3, and added tests cases to make sure that all the new environments match the corresponding old ones.

**Comment by pzhokhov** [comment]
there were some issues with the tests requiring mujoco; I have added respective skip modifiers and made a new PR: https://github.com/openai/gym/pull/1328. Unfortunately, I squash-merged your branch instead of merging it; which removed commit history. Feel free to either update your PR with the changes (the only changes are in `gym/env/tests/spec_list.py` and `gym/envs/tests/test_mujoco_v2_to_v2_conversion.py`

**Comment by hartikainen** [comment]
@pzhokhov I merged your changed into this branch and at the same time rebased this one from master. Let me know if there's anything else that needs to change.

**Comment by pzhokhov** [comment]
Awesome, thanks! Merging

**Comment by hartikainen** [comment]
Nice, thanks @pzhokhov!

**Pull request merged**
