### PR TITLE
Fix CarRacing termination

### PR DESCRIPTION
**Pull request by araffin**
# Description

Fix CarRacing termination (both reaching end of lap and treating it not like a failure).

See https://github.com/openai/gym/pull/2525#discussion_r873539773

EDIT: need to be merged after https://github.com/openai/gym/pull/2888

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Screenshots
Please attach before and after screenshots of the change if applicable.

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by pseudo-rnd-thoughts** [comment]
How long has this bug been in the environment? Does this need a version bump just in case?

**Comment by araffin** [comment]
> How long has this bug been in the environment? Does this need a version bump just in case?

The timeout not treated properly? forever...
The other one, since https://github.com/openai/gym/pull/2888 (actually https://github.com/openai/gym/pull/2888 was supposed to fix two things, but only fixed one).

> Does this need a version bump just in case?

Probably yes. (the models trained on previous versions will still work on that one, and the other way around though)

**Comment by araffin** [comment]
> Would you be able to make the version bump and add a comment to the version info in the docstring

Where exactly should I do that?
(it will probably be faster if you do it directly and push the commit to my PR ;))

**Comment by araffin** [comment]
This has been merged before the version bump...

**Pull request merged**
