### PR TITLE
add pygame GUI for frozen_lake.py env

### PR DESCRIPTION
**Pull request by younik**
Continuing from #2566
I fixed diff problem

### CODE REVIEW

**Comment by jkterry1** [comment]
@younik can you please fix tests?

**Comment by younik** [comment]
> @younik can you please fix tests?

Now it should work

**Comment by younik** [comment]
Current appearance:
Screenshot from 2022-02-03 14-32-48

**Review by trigaten — APPROVED** [review]
I ran it locally; LGTM.

**Pull request merged**
