### PR TITLE
Cleanup, removal of unmaintained code

### PR DESCRIPTION
**Pull request by joschu**
Made some aesthetic improvements and removed unmaintained parts of gym. This may seem like a downgrade in functionality, but it is actually a long-needed cleanup in preparation for some great new things that will be released in the next month.

    + Now your `Env` and `Wrapper` subclasses should define `step`, `reset`, `render`, `close`, `seed` rather than underscored method names.
    + Removed the `board_game`, `debugging`, `safety`, `parameter_tuning` environments since they're not being maintained by us at OpenAI. We encourage authors and users to create new repositories for these environments.
    + Changed `MultiDiscrete` action space to range from `[0, ..., n-1]` rather than `[a, ..., b-1]`.
    + No more `render(close=True)`, use env-specific methods to close the rendering.
    + Removed `scoreboard` directory, since site doesn't exist anymore.
    + Moved `gym/monitoring` to `gym/wrappers/monitoring`
    + Add `dtype` to `Space`.
    + Not using python's built-in module anymore, using `gym.logger`

### CODE REVIEW

**Comment by jachiam** [comment]
Seems like some of these changes are breaking---maybe a version bump is in order?

**Comment by wenkesj** [comment]
@joschu thank you for caring 🙏🏻

**Comment by LukeWood** [comment]
Hey @joschu, this breaks CarRacing-v0.   Just a heads up.

**Comment by chuchuhao** [comment]
Hi, what is the different between `space.MultiDiscrete` and `space.Discrete` after this changed ?

**Comment by LukeWood** [comment]
Just a heads up - made some changes to CarRacing-v0 to address the problems introduced by the spec upgrade.

PR:
https://github.com/openai/gym/pull/924

**Pull request merged**
