### PR TITLE
fix build by disabling mujoco and moving to newer python patch versions

### PR DESCRIPTION
**Pull request by pzhokhov**
moving to newer python patch versions is necessary to avoid timeouts when pulling docker images for them (somehow, newer images provide better bandwidth? Or maybe old images are not hosted anymore at all?). At the same time, mujoco segfaults on 3.6.13 and 3.7.10. Hence, this PR disables mujoco tests.

### CODE REVIEW

**Comment by dciborow** [comment]
please get this in so a new version of gym can go out before i have to pull it from my project....

**Comment by dciborow** [comment]
@joschu , @christopherhesse , I am trying to get a new release of for this PR #2189 , but believe we need reviews from you for this one before a release can be made?

**Review by joschu — APPROVED** [review]

**Comment by dciborow** [comment]
@pzhokhov , we got an ack! Are we able to move forward with release?

**Comment by vi3itor** [comment]
@pzhokhov Thank you for the updates! I very much need this PR to be accepted for [google-research/football](https://github.com/google-research/football) because of the same issue as #2203. Do you need @christopherhesse approval to release a new version?

**Comment by dciborow** [comment]
@joschu , @pzhokhov , 
Understand this repo is mostly in maintenance mode. My team would rather have an internal fork of this that we can keep secure ourselves. But as I am going to be doing the work regardless, it would actually be even easier for me if I could be an admin in the repo and set up dependabot for the package. 
Right now we are still in testing, so this is more of a test case for us then a blocker. But at this point, we aren't sure if we could get real updates out as fast as we need. 

Is there any interest in having some help on the build release side of this package so that next time we can roll an update for this out faster?

**Comment by pzhokhov** [comment]
@dciborow thanks for the ping! While external maintenance could benefit the quality of the maintenance, unfortunately, our security team is not comfortable with giving admin access outside the org.

**Comment by pzhokhov** [comment]
also, released a new version :)

**Pull request merged**
