### PR TITLE
Extending the OpenAI Gym for robotics

### PR DESCRIPTION
**Pull request by vmayoral**
For those familiar with ROS and Gazebo, here's a contribution that could be useful. Feel free to rebase the code if desired but we'd appreciate a reference to the original author's work.

This work was summarized at *Extending the OpenAI Gym for robotics: a toolkit
for reinforcement learning using ROS and Gazebo* whitepaper.

**Update: here's the official white paper in ArXiv: [Extending the OpenAI Gym for robotics: a toolkit
for reinforcement learning using ROS and Gazebo](https://arxiv.org/abs/1608.05742)**

### CODE REVIEW

**Comment by tlbtlbtlb** [comment]
This is an exciting project!

I suspect the strategy of `unpause_physics`, `wait_for_message`, `pause_physics` won't give a deterministic amount of simulated time between steps. I believe Gazebo allows more explicit control over simulated time. Have you thought through all the tradeoffs here?

The current pull request has some bugs including syntax errors that you can see in the Travis CI test. Can you fix those up and resubmit?

**Comment by vmayoral** [comment]
Glad to hear that @tlbtlbtlb!

We actually weren't sure of whether you'd be interested so I just rebased our working branch on top of your latest commits. Something probably went wrong in the way. We'll do a bit of testing and send another PR. 

@Nestor94Gonzalez, @IkerZamora, can you help with this?

Leaving this open for now.

**Comment by Nestor94Gonzalez** [comment]
@tlbtlbtlb 
> I suspect the strategy of unpause_physics, wait_for_message, pause_physics won't give a deterministic amount of simulated time between steps. I believe Gazebo allows more explicit control over simulated time. Have you thought through all the tradeoffs here?

We chose simulation speed over deterministic amount of steps. We will try to fix this without reducing simulation speed significantly.

**Comment by olegklimov** [comment]
Oh, Erle Robotics! Nice to hear from you, I've bought an autopilot board from you.

Did you manage to learn some policy on simulator, transfer on real robot, yourselves? Do you have a youtube clip, that would be interesting.

I also noticed all your actions are discrete (forward, left, right)? I'd suggest you also make continuous versions, too. Code I'm experimenting with don't even have discrete actions support anymore.

Can your code run hardware-in-the-loop on simulator?

And some random thoughts... There are a lot of maze environments in your whitepaper. RL is hardly a proper way to navigate a maze, and SLAM is heavy. I think more simple tasks people can run in emulator are needed. But it's just me, other people can have other opinions.

**Comment by Nestor94Gonzalez** [comment]
Hi @olegklimov ,

Here you have an execution example video : https://www.youtube.com/watch?v=8hxCBkgp95k
And this is the whitepaper: http://erlerobotics.com/whitepaper/robot_gym.pdf

We will be using neural networks in order to use continuous data. Once we manage to do this, we will transfer training data to a real robot.

**Comment by tlbtlbtlb** [comment]
With the influx of new environments, we figure it's best to split major new environments into separate repos. For example we just created [gym-soccer](http://github.com/openai/gym-soccer). Could you do the same here? I suggest the name gym-gazebo since gym-robotics and gym-ros are already underway (but not released yet). (gym-ros is intended for real-time operation of physical robots, so it has a more complicated control structure)

[gym/envs/README.md](https://github.com/openai/gym/blob/master/gym/envs/README.md) has a checklist for creating new environments, and [gym-soccer](http://github.com/openai/gym-soccer) is a working example.

**Comment by vmayoral** [comment]
Fair enough @tlbtlbtlb. Updated the repository name to `gym-gazebo` https://github.com/erlerobot/gym-gazebo.

**Comment by tlbtlbtlb** [comment]
But the idea is to not also have a copy of the rest of gym in there. It should be just your environments in your repo, and import gym for the common infrastructure.

**Comment by Nestor94Gonzalez** [comment]
We have updated [erlerobot/gym-gazebo](https://github.com/erlerobot/gym-gazebo/). The structure follows the one used in [gym-soccer](https://github.com/openai/gym-soccer). 

We are currently trying to teach the Turtlebot robot how to avoid obstacles using CNN. We have tried many network configurations but we have not achieved good results so far. Any advice and suggestions will be greatly appreciated. https://github.com/erlerobot/gym-gazebo/issues/5

**Comment by tlbtlbtlb** [comment]
Closing this PR, since development is now happening in https://github.com/erlerobot/gym-gazebo/

**Pull request closed without merging**
