### PR TITLE
Add CliffWalking environment

### PR DESCRIPTION
**Pull request by quanvuong**
I'd like to add the Cliff Walking environment to toy_text.

The mechanics of the environment is adapted from Example 6.6 (page 145) from Reinforcement Learning: An Introduction by Sutton and Barto: http://people.inf.elte.hu/lorincz/Files/RL_2006/SuttonBook.pdf

Running the following code to test the environment gives the following result:

```
import gym
import itertools

env = gym.make('CliffWalking-v0')

print(env)

for i_episode in range(1):
    observation = env.reset()
    for t in itertools.count():
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print('Episode finished after {} timesteps'.format(
                t+1
            ))
            break

```
```
<CliffWalkingEnv<CliffWalking-v0>>
...
34
o  o  o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  x  o  o
o  C  C  C  C  C  C  C  C  C  C  T

33
o  o  o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  x  o  o
o  o  o  o  o  o  o  o  o  o  o  o
o  C  C  C  C  C  C  C  C  C  C  T

21
o  o  o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o  x  o
o  o  o  o  o  o  o  o  o  o  o  o
o  C  C  C  C  C  C  C  C  C  C  T

22
o  o  o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o  x  o
o  C  C  C  C  C  C  C  C  C  C  T

34
o  o  o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o  o  x
o  C  C  C  C  C  C  C  C  C  C  T

35
Episode finished after 9581 timesteps
```

### CODE REVIEW

**Comment by quanvuong** [comment]
The test that failed has to do with KellyCoinflip-v0 and KellyCoinflipGeneralized-v0 not giving the [expected observation](https://travis-ci.org/openai/gym/builds/232374955#L3279), though I didn't touch these environments. Can I have some pointers to fix the failing test ? 

Also, running `pytest` in the gym directory as mentioned [here](https://github.com/openai/gym/pull/581) by @tlbtlbtlb does not reproduce the failing test (all tests passed).

**Comment by tlbtlbtlb** [comment]
They were failing only for Python2. I'm about to check in a fix. In general, you should run both
```
python2 -m pytest
python3 -m pytest
```
in the gym directory.

**Comment by tlbtlbtlb** [comment]
I checked in the fix to master. If you rebase from master and submit the PR again, it should work.

**Comment by quanvuong** [comment]
Yup the test passed. I'll document the environment in gym wiki if the PR is accepted. Thanks!

**Comment by tlbtlbtlb** [comment]
Looks good to me. Any objection @joschu ?

**Comment by joschu** [comment]
nope, looks good

**Comment by tlbtlbtlb** [comment]
Merged (along with tests) as #590

**Pull request closed without merging**
