### PR TITLE
Adding Frame Normalization in Atari Pre-Processing

### PR DESCRIPTION
**Pull request by koulanurag**
related to #1679

### CODE REVIEW

**Comment by koulanurag** [comment]
#1680

**Comment by pzhokhov** [comment]
I like this, but please add a unit test

**Comment by zuoxingdong** [comment]
Hi @koulanurag @pzhokhov , it might be nice to add some warning in docstring about `Scale observation`, because if it's turned on, then the benefits of `FrameStack` memory optimization will break. So at least provide this warning in the documentation might be nice for the users.

**Comment by koulanurag** [comment]
Hi @pzhokhov @zuoxingdong 

I have added the unit test cases and the required message in the docstring.

**Pull request merged**
