### PR TITLE
box2d kengz vs py

### PR DESCRIPTION
**Pull request by pzhokhov**
use box2d-py instead of box2d-kengz; and enable tests of environments that use box2d

### CODE REVIEW

**Comment by christopherhesse** [comment]
Looks good, but https://github.com/openai/gym/blob/74229c8dc289e07a515740e3652573bab060ea52/tox.ini references box2d-py directly, but it seems like a test script should use the dependencies specified in setup.py, right?

**Comment by pzhokhov** [comment]
yeah, that's also a good point... let me try to rework tox.ini a bit

**Comment by christopherhesse** [comment]
Nice!  You left pachi-py and doom_py in there, are those unused at this point?

**Comment by pzhokhov** [comment]
more like I did not know what will happen if I remove them. but as we are cleaning up, might as well try and see :)

**Comment by DuaneNielsen** [comment]
Just so you know, I had to go back to box2d-kengz to get the gym environment working.. with the default box2d I get the missing LIMIT_RAND error on mac.

**Pull request merged**
