### PR TITLE
Remove step initialization for mujoco obs spaces

### PR DESCRIPTION
**Pull request by rodrigodelazcano**
remove step initialization for mujoco obs space

pre-commit

# Description

Remove the use of stepping in the mujoco environment base class to obtain the observation space. Instead, instantiate the fixed observation space of each environment  in their respective child class.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Screenshots
Please attach before and after screenshots of the change if applicable.

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by pseudo-rnd-thoughts — CHANGES_REQUESTED** [review]
The changes generally look good. Would you be able to add a test in `tests/envs/test_mujoco.py` that parameterizes over all of the mujoco environment with all of the modifying parameters to check that the observation shape is equal to the env obs space

**Comment by rodrigodelazcano** [comment]
Just added the pytest function. Please let me know if anything else is required.

**Comment by albertcthomas** [comment]
Thanks @rodrigodelazcano ! We were subclassing some mujoco envs and we were reimplementing the step method. The issue for us was that this method (our step method) was being called when we were calling __init__ of the parent gym mujoco env and this was causing issue as not calling the parent step method. In the end we had to do this in a different way. This change should make things smoother!

**Comment by rodrigodelazcano** [comment]
Hey @albertcthomas ! I'm glad this helped on your research. Please let us know if you face any more issue to improve the mujoco envs :)

**Pull request merged**
