### PR TITLE
Brings back compatible function.

### PR DESCRIPTION
**Pull request by wojzaremba**

### CODE REVIEW

**Comment by machinaut** [comment]
It'd be nice to get some tests with this.

Like some examples of compatible and incompatible spaces.

**Comment by joschu** [comment]
I don't think this belongs in gym. Why not just write a free function with some if statements?

**Comment by joschu** [comment]
My objection is that it's not clear what "compatible" means, or what it's used for.

**Comment by pzhokhov** [comment]
@wojzaremba @lilianweng is this PR still relevant / useful? If so, I'd be happy to talk about including it / resolving current merge conflicts

**Pull request closed without merging**
