### PR TITLE
added continuous mountain car v0

### PR DESCRIPTION
**Pull request by osigaud**
This new environment directly derives from the gym MountainCar environment (same structure, same render function), but with continuous action (force) control. The force action is taken from the MountainCar Environment from the "FAReinforcement" library of Jose Antonio Martin H. (version 1.0), adapted by  'Tom Schaul, tom@idsia.ch' and then modified by Arnaud de Broissia.

I believe it is useful because there are very few small continuous state/continuous action problems in gym so far (apart from pendulum).

### CODE REVIEW

**Comment by olegklimov** [comment]
I actually came to the same idea: it's nice to have continuous version of simple environments, I have/use LunarLanderContinuous for a while, probably should do a PR...

**Comment by tlbtlbtlb** [comment]
MountainCar is sort of a degenerate case of continuous action spaces, as the optimal policy consists of only actions at the + or - limit. But maybe it's a reasonable addition for testing continuous action policies.

**Comment by olegklimov** [comment]
Posted `LunarLanderContinuous` I mentioned earlier, in #307. Environments are exactly the same, only control method that is different.

**Comment by osigaud** [comment]
I forgot to mention that the reward function in this instance of continuous mountain is such that you should reach the goal using as few energy (sum of squared actions, in practice) as possible. That's different from reaching the goal as fast as possible, and in this case the bang-bang control is not optimal, to answer Trevor Blackwell's comment.

**Comment by gdb** [comment]
It does seem like this would be useful, and this is well-implemented. Thanks!

**Pull request merged**
