### PR TITLE
Suit ConvergenceControl-v0 to tensorflow backend.

### PR DESCRIPTION
**Pull request by XericZephyr**
At present, the `ConvergenceControl-v0` environment does not support tensorflow backend. 

Mostly because the image dimension orders are different between tensorflow and theano.

This PR try to fix that with tensorflow backend.

### CODE REVIEW

**Comment by tlbtlbtlb** [comment]
Does this break using Theano as a backend? Do we want to support Theano here?

**Comment by XericZephyr** [comment]
@tlbtlbtlb  Do we have any unit test for it? In principle, it should work with Theano.

**Comment by tlbtlbtlb** [comment]
@iaroslav-ai This is your code, do you know what you want to do about Theano/Tensorflow here?

**Comment by XericZephyr** [comment]
@iaroslav-ai @tlbtlbtlb Also let me know if there are additional unit/lint tests required.

**Comment by iaroslav-ai** [comment]
@XericZephyr Thanks for the PR! Can confirm that that it runs fine using both theano and tensorflow.
As for a test, I could imagine something like this could work:
Make a file "test.py":
```
import gym

env = gym.make('ConvergenceControl-v0')

for episode in range(3):
    o = env.reset()
    for step in range(7):
        env.step(env.action_space.sample())
        env.render()
```
Make a bash file "run.sh":
```
THEANO_FLAGS=device=gpu KERAS_BACKEND=tensorflow python test.py
THEANO_FLAGS=device=gpu KERAS_BACKEND=theano python test.py
```
If run.sh completes successfully, then the code works fine. This assumes that the code is tested on Ubuntu. 
It would probably be good to have such test around. But one could also just say that only tensorflow is (officially) supported and target tensorflow only. 
@tlbtlbtlb the code is compatible with both Theano and Tensorflow I propose to keep it as it is.

**Comment by tlbtlbtlb** [comment]
Ideally, the test should determine that they get similar answers from tf and Theano. We do this for most environments: see gym/gym/envs/tests/test_envs_semantics.py.

**Comment by XericZephyr** [comment]
@iaroslav-ai  Thanks for the confirmation. Your original env looks interesting and charming. I am looking forward to testing it on my end.

@tlbtlbtlb After looking into the code, I am still bit confused on how to use the pytest. (I used to be heavily leaned on `nosetests`. ) Do you have any example on how to produce those tests for specific env? Thanks.

**Comment by XericZephyr** [comment]
Any update comment on this PR? @tlbtlbtlb Thanks.

**Comment by XericZephyr** [comment]
Closed for now due to inactivity.

**Pull request closed without merging**
