### PR TITLE
Added pendulumV2 with SI units

### PR DESCRIPTION
**Pull request by abhinavsagar**

### CODE REVIEW

**Comment by abhinavsagar** [comment]
@pzhokhov Ping

**Comment by pzhokhov** [comment]
two points: 1) this seems largely duplicated with regular Pendulum-v0 and 2) the registration code is not present (see `gym/envs/__init__.py`). In light of those two, here's what I suggest - make physics parameters to be constructor kwargs for pendulum that default to values in Pendulum-v0; and register an environment Pendulum-v1 with SI values passed via kwargs. Does that make sense?

**Comment by abhinavsagar** [comment]
Closing this. Opening the new one .

**Comment by abhinavsagar** [comment]
Closing this. Opening new one with required changes.

**Pull request closed without merging**
