### PR TITLE
A series of super simple environments for debugging agents

### PR DESCRIPTION
**Pull request by RafaelCosman**
These environments all have known optimal policies and value functions. They are intended to help developers verify that, for example, their value function is converging on the true value function. These important properties are sometimes difficult to verify on even simple environments like PoleCart.

It seems like all pulls are failing the CI tests right now, but on my machine this PR passes all nose2 tests. Result of running `nose2`:

```
2016-05-26 11:16:50.900 Python[56002:4355192] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/0k/h5s9v3m56kq6d9v7nj7b_vr00000gn/T/org.python.python.savedState
.............................................Initializing Pachi engine uct with args threads=1,pondering=0
Initializing Pachi engine uct with args threads=1,pondering=0
.......................Initializing Pachi engine uct with args threads=1,pondering=0
Initializing Pachi engine uct with args threads=1,pondering=0
......................................................................................................................................................Initializing Pachi engine uct with args threads=1,pondering=0
Initializing Pachi engine uct with args threads=1,pondering=0
Initializing Pachi engine uct with args threads=1,pondering=0
.......................Initializing Pachi engine uct with args threads=1,pondering=0
Initializing Pachi engine uct with args threads=1,pondering=0
Initializing Pachi engine uct with args threads=1,pondering=0
...........................................................................................................
----------------------------------------------------------------------
Ran 348 tests in 55.073s

OK
```

### CODE REVIEW

**Comment by jietang** [comment]
Thanks @RafaelCosman, these look great. Could you remove the tasks from gym/scoreboard/__init__.py - then they will be local-only debugging tasks that cannot be submitted.

Alternatively, if yo think it would be useful to allow gym submissions, could you implement a _render() method that supports the ['ansi', 'human'] rendering modes? That will allow us to generate visuals on the website.

**Comment by RafaelCosman** [comment]
@jietang, thanks for your comment. I don't want the debugging envs to be on the website, but when I remove the registrations from scoreboard/__init__.py I get the following error: ```Site environment registry incorrect: Scoreboard did not register all envs: set(['TwoRoundNondeterministicReward-v0', 'OneRoundDeterministicReward-v0', 'TwoRoundDeterministicReward-v0', 'OneRoundNondeterministicReward-v0'])```

**Comment by jietang** [comment]
@RafaelCosman Yes I forgot about that. Let's add an exception in gym/scoreboard/registration.py to skip over gym envs in the debugging folder.

**Comment by gdb** [comment]
Why don't we add this as a `local_only` flag on `register`?

**Comment by jietang** [comment]
Oh I like the local_only flag approach better. Let's do that.

**Comment by RafaelCosman** [comment]
@jietang @gdb thanks for the comments. Implemented `local_only`, ready for review.

**Comment by jietang** [comment]
Thanks @RafaelCosman

**Comment by RafaelCosman** [comment]
Thanks for merging, @jietang!

BTW, why roll this whole thing into a single 200+ line commit? I'd at least keep the `local_only` part separate from everything else.

**Comment by jietang** [comment]
Yes you're right that would have been better to split the commits (little lazy with my squashing). I'll try to be better next time :)

**Comment by RafaelCosman** [comment]
Also, @jietang, with open source projects it's good form to let people get contributor credit for their work by letting them squash their own commits and then merging their PR rather than squashing them yourself and committing them yourself.

**Comment by jietang** [comment]
@RafaelCosman, yes I agree. I apologize for not merging this PR in a way that accurately reflected the authorship chain. I think for gym to be maximally successful it requires the contributions of the community, and maintaining contributor credit is one way for us to show our appreciation.

For context, my goal at this point in the project's lifecycle is to bias for moving quickly. To that end I will sometimes manually merge in PRs (for instance if there are merge conflicts) rather than waiting for a perfectly packaged contributor PR. Going forward, if I'm merging manually I'll plan to merge without squashing in order to avoid disrupting history (if you're up for it, it would be helpful if you could rebase/squash before submitting the PR)

**Comment by RafaelCosman** [comment]
Thanks @jietang. Really appreciate your work on this project and definitely agree with moving quickly. I'll try to rebase/squash before submitting PRs.

**Pull request closed without merging**
