### PR TITLE
expand cloudpickle range

### PR DESCRIPTION
**Pull request by pzhokhov**

### CODE REVIEW

**Comment by jachiam** [comment]
LGTM!

**Comment by araffin** [comment]
@pzhokhov is there a reason to cap the version to 1.4.0?
Could we extend it to more recent versions?

**Comment by pzhokhov** [comment]
I suspect the main reason was that 1.3 was the latest minor version at the time of this PR, and we did not want to leave upper version open - in case the cloudpickle API were to change in later releases.

**Comment by pzhokhov** [comment]
it seems like all our tests are passing with the latest (1.6.0) cloudpickle, if that's a desired change, we can merge it into master

**Pull request merged**
