### PR TITLE
lunarlander add rendering back to test_lunar_lander.py

### PR DESCRIPTION
**Pull request by pzhokhov**

### CODE REVIEW

**Comment by pzhokhov** [comment]
oh ok so you want it it lunar_lander.py :) no worries

**Comment by pzhokhov** [comment]
@olegklimov is that good ? Anything else that is not quite right?

**Comment by olegklimov** [comment]
Perfect!

No, not perfect. One thing I still see as a problematic, 'enjoy' usually means trained policy. In this case, it is heuristic, not a trained policy.

**Comment by pzhokhov** [comment]
picky you are, sir :) renamed enjoy_lander into demo_heuristic_lander

**Pull request merged**
