### PR TITLE
Remove CarRacing environment from Box 2D

### PR DESCRIPTION
**Pull request by carlosluis**
### Description

- Removes `CarRacing` and `Car` from Box 2D
- If someone tries to import `CarRacing` via `from gym.envs.box2d.car_racing import CarRacing`, they will see a warning.
- If they try to import implicitly from the box2d package, they will see an `ImportError` due to [this missing Box2D class](https://github.com/openai/gym/blob/e5d1ba9a4c532603a4b08ba6dae624188287e69b/gym/envs/box2d/__init__.py#L2)

### Testing
- Verified behaviour when trying to import `CarRacing`.

### Question
1.  I'm probably missing some context on why the other environments in box2d still exist when there's no `Box2D` class anymore. Is the plan to remove them all eventually?
2. Since I couldn't find examples of other removed envs, not sure if there's a minimum of functionality that should be left in the class. Currently it only raises a warning as soon as it's imported, but any call to the env will fail of course

### CODE REVIEW

**Comment by RedTachyon** [comment]
Is this related to some issue/discussion that I'm not seeing? Why is this environment being removed?

As far as I remember, the plan is to replace Box2D with something more sane eventually, but I don't see why one of the environments should be removed ahead of time. And simply removing Box2D without a replacement would be a bad move since LunarLander and BipedalWalker both are pretty useful to have.

**Comment by jkterry1** [comment]
Hey, apparently something got lost in translation somewhere. Basically the plan is to remove CarRacing (you can check stats for imports on github, its virtually used), conduct a bunch of maintenance/refactoring to lunar lander and bipedal walker and then use them as the basis of new phys2d environments. Essentially the motivation for removal is that I'd rather remove it than expend the time/energy on rewriting it in brax and the large list of maintenance needed before that could be done.

**Comment by jkterry1** [comment]
@carlosluis can you please fix CI?

**Comment by jkterry1** [comment]
One important piece of historical context behind these environments for those who read this is that, according to OpenAI, the box2d environments came from "some random dude who we'd never met before who created a PR and we thought they were kinda of cool so we merged them." There is no real compelling ideological reason behind including these like some other environments we have in Gym.

**Comment by araffin** [comment]
> Hey, apparently something got lost in translation somewhere. Basically the plan is to remove CarRacing (you can check stats for imports on github, its virtually used), 

virtually used?
https://github.com/search?q=carracing-v0&type=repositories
58 repos and 3k files that refer to "Carracing-v0"...

**Comment by jkterry1** [comment]
Antonin pointed out this work in discussion over discord:

https://arxiv.org/pdf/1809.01999.pdf and the importance of this for LSTMs work on RL, both of which I was unaware of. We'll keep this environment in and conduct the same maintenance on it as the other box2d environments.

@carlosluis Would you mind taking a look at this issue? https://github.com/openai/gym/issues/2099

**Pull request closed without merging**
