### PR TITLE
Improved performance of simulation

### PR DESCRIPTION
**Pull request by leocus**
I reduced the time required for the simulation by using vertex_lists in pyglet

### CODE REVIEW

**Comment by pzhokhov** [comment]
very cool, thanks! I allowed myself some style changes to match the updated style upstream. 
@leocus could you share some numbers about the performance change? 
@olegklimov any chance you could take a look and see if the changes make sense to you? I don't know gl well enough to judge that.

**Comment by olegklimov** [comment]
> time required for the simulation 

That's cool! How much the render time has improved?

**Comment by leocus** [comment]
On my setup (i5-8250U, 16GB RAM DDR4) i measured those times (over 100 simulations):

- Original version: 
    - Mean: 8.92 s/simulation
    - Std: 0.59 s/simulation
- This pull request: 
    - Mean: 3.84 s/simulation
    - Std: 0.25 s/simulation

**Comment by xeviknal** [comment]
This PR introduced this nasty memory leak: #2062
A community member created a PR to approach this: https://github.com/openai/gym/pull/2096

Nice enhancement btw!

**Comment by leocus** [comment]
Sorry about that, glad it has been fixed :)

**Pull request merged**
