### PR TITLE
SpaceX-style Falcon rocket landing on drone-ship, proposed to the suite of box2d envs 

### PR DESCRIPTION
**Pull request by vBarbaros**
Hey guys!

I've assembled a Falcon rocket that can learn to land itself on the autonomous floating drone ship. I reused a part of the LunarLander (literally, the lander) and added some more elements so that it makes the task more difficult and more interesting.

The state-dimensions contains now 13 params, some of which are part of the drone-ship. The difficulty of the task can be managed in many ways (e.g., adding more/less power to rocket's engines, increasing/decreasing drone's force that pushes it around, so that it oscillates from left to right and back with different velocity, etc).

The reward function accounts for the falcon rocket landing on both legs (otherwise it's not quite a landing), for the angle and the velocity of the drone ship (higher speed, more unstable drone ship, higher the reward); the episodes are done once the rocket has landed, or if the rocket goes below the drone ship level.

You can land the SpaceX Falcon rocket from the keyboard - just comment out the `heuristic()` method call at `line 485` and uncomment the line below `line 486` with `keyboard()` method call.

Hope you'll like it!

Thanks,
Victor

p.s.: If accepted, I'll add more explanations, and any suggestions for improvement are welcomed, of course!

### CODE REVIEW

**Comment by olegklimov** [comment]
Hi @vBarbaros ! Do you have a video?

**Comment by vBarbaros** [comment]
I can get one quickly. Do you want me to push it in the same folder with the script?

**Comment by olegklimov** [comment]
No, just put it somewhere (on youtube for example).

**Comment by vBarbaros** [comment]
here we go [https://www.youtube.com/watch?v=sg-6g9DtfrY&feature=youtu.be](url)

**Comment by olegklimov** [comment]
Oh, OK. I'm not sure about research value though. Changes in environment seem to be minimal.

**Comment by vBarbaros** [comment]
@olegklimov , so the real changes are under the hood: the state dimensions go from 8 (in LunarLander) to 13, also the constraints a trickier (I still need to add the constraints on the x-axis as well). While the Lander was mainly "land-it-as-smooth-as-possible" type of task, here we have a "shoot-a-moving-target" type of task, roughly described.

The autonomous boat will not be in the left corner for long time, and the velocity with which it "floats" can vary as well. Other parameters, rocket and/or drone-ship related can be tuned so that the elements become more or less stable. There could be designed quite a lot of more "realistic" tasks from this perspective.

Let me know if still interesting!

Thank you

**Comment by olegklimov** [comment]
Yeah, great. Let's wait for someone else to comment here.

**Comment by vBarbaros** [comment]
just in case someone is interested, here is how the refined version looks like [here](https://www.youtube.com/watch?v=GpHylnSox_Q)

**Comment by pzhokhov** [comment]
@vBarbaros sorry for lack of response. Our current policy is not to include new environments into the gym, and rather recommend them to be created as separate projects / packages. If you decide to go that route , I'll gladly add a reference to this project to environments.md file. Closing this; @olegklimov feel free to object / override

**Comment by algebraic-mouse** [comment]
@vBarbaros this environment seems to have potential as a testbed for online/continual learning agents. Have you created this under a separate repository?

**Comment by vBarbaros** [comment]
Thanks for your interest, @algebraic-mouse !
You can check it, and many others, here: https://github.com/Breakend/gym-extensions.git

**Pull request closed without merging**
