### PR TITLE
Properly check whether AttributeError is caused by render_mode

### PR DESCRIPTION
**Pull request by Markus28**
@pseudo-rnd-thoughts 

Atm the if statement will be triggered by any attribute error, regardless of which kwarg caused it.

### CODE REVIEW

**Comment by RedTachyon** [comment]
Shouldn't it be `>= 0`?

**Comment by Markus28** [comment]
Yeah it doesn't really matter in practice because the string will be preceded by the signature of the method that caused the error. But I can change it to >=, that's probably more understandable

**Comment by pseudo-rnd-thoughts** [comment]
Could you add a short test because it is a confusing error if it is not for the correct reason

**Comment by pseudo-rnd-thoughts** [comment]
LGTM

**Pull request merged**
